# Generated by Django 5.2.4 on 2025-07-07 21:52

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcareprofessionalprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='healthcareprofessionalprofile',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Currently accepting new patients'),
        ),
        migrations.AddField(
            model_name='healthcareprofessionalprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='bed_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Number of beds (for hospitals)', null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='staff_count',
            field=models.PositiveIntegerField(blank=True, help_text='Total number of staff', null=True),
        ),
        migrations.AddField(
            model_name='institutionprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='county',
            field=models.CharField(blank=True, choices=[('baringo', 'Baringo'), ('bomet', 'Bomet'), ('bungoma', 'Bungoma'), ('busia', 'Busia'), ('elgeyo_marakwet', 'Elgeyo-Marakwet'), ('embu', 'Embu'), ('garissa', 'Garissa'), ('homa_bay', 'Homa Bay'), ('isiolo', 'Isiolo'), ('kajiado', 'Kajiado'), ('kakamega', 'Kakamega'), ('kericho', 'Kericho'), ('kiambu', 'Kiambu'), ('kilifi', 'Kilifi'), ('kirinyaga', 'Kirinyaga'), ('kisii', 'Kisii'), ('kisumu', 'Kisumu'), ('kitui', 'Kitui'), ('kwale', 'Kwale'), ('laikipia', 'Laikipia'), ('lamu', 'Lamu'), ('machakos', 'Machakos'), ('makueni', 'Makueni'), ('mandera', 'Mandera'), ('marsabit', 'Marsabit'), ('meru', 'Meru'), ('migori', 'Migori'), ('mombasa', 'Mombasa'), ('murang_a', "Murang'a"), ('nairobi', 'Nairobi'), ('nakuru', 'Nakuru'), ('nandi', 'Nandi'), ('narok', 'Narok'), ('nyamira', 'Nyamira'), ('nyandarua', 'Nyandarua'), ('nyeri', 'Nyeri'), ('samburu', 'Samburu'), ('siaya', 'Siaya'), ('taita_taveta', 'Taita-Taveta'), ('tana_river', 'Tana River'), ('tharaka_nithi', 'Tharaka-Nithi'), ('trans_nzoia', 'Trans Nzoia'), ('turkana', 'Turkana'), ('uasin_gishu', 'Uasin Gishu'), ('vihiga', 'Vihiga'), ('wajir', 'Wajir'), ('west_pokot', 'West Pokot')], max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, help_text='Upload a profile photo (recommended size: 400x400px)', null=True, upload_to=accounts.models.user_profile_photo_path),
        ),
        migrations.AddField(
            model_name='user',
            name='subcounty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='healthcareprofessionalprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Brief professional biography'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessionalprofile',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Consultation fee in KES', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='healthcareprofessionalprofile',
            name='specialization',
            field=models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('surgery', 'Surgery'), ('gynecology', 'Gynecology'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('dentistry', 'Dentistry'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('physiotherapy', 'Physiotherapy'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='institution_type',
            field=models.CharField(choices=[('clinic', 'Clinic'), ('hospital', 'Hospital'), ('diagnostic_center', 'Diagnostic Center'), ('pharmacy', 'Pharmacy'), ('laboratory', 'Laboratory')], max_length=20),
        ),
        migrations.AlterField(
            model_name='institutionprofile',
            name='operating_hours',
            field=models.TextField(blank=True, help_text='Operating hours and days'),
        ),
    ]
