# Generated by Django 5.2.4 on 2025-07-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_healthcareprofessionalprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprofessionalprofile',
            name='specialization',
            field=models.CharField(choices=[('general_practice', 'General Practice'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('surgery', 'Surgery'), ('gynecology', 'Gynecology'), ('orthopedics', 'Orthopedics'), ('neurology', 'Neurology'), ('oncology', 'Oncology'), ('dentistry', 'Dentistry'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, Throat)'), ('radiology', 'Radiology'), ('pathology', 'Pathology'), ('anesthesiology', 'Anesthesiology'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine'), ('nursing', 'Nursing'), ('pharmacy', 'Pharmacy'), ('physiotherapy', 'Physiotherapy'), ('medical Officer', 'Medical Officer'), ('clinical_officer', 'Clinical Officer'), ('nutrition', 'Nutrition'), ('occupational_therapy', 'Occupational Therapy'), ('other', 'Other')], max_length=50),
        ),
    ]
